# Generated by Django 4.1.3 on 2022-11-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bash_video',
            name='video',
            field=models.FileField(upload_to='videos'),
        ),
    ]
