# Generated by Django 4.1.3 on 2022-11-30 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0003_uniwersity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='uniwersity',
            new_name='uniwersity_TKM',
        ),
    ]
