# Generated by Django 4.1.3 on 2022-11-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0004_rename_uniwersity_uniwersity_tkm'),
    ]

    operations = [
        migrations.CreateModel(
            name='uniwersity_GLOBAL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.CharField(max_length=200)),
                ('surat', models.FileField(upload_to='images')),
                ('beyan', models.TextField()),
            ],
        ),
    ]
