# Generated by Django 4.1.3 on 2022-11-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0005_uniwersity_global'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uniwersity_global',
            name='beyan',
        ),
        migrations.RemoveField(
            model_name='uniwersity_tkm',
            name='beyan',
        ),
        migrations.AddField(
            model_name='uniwersity_global',
            name='link',
            field=models.URLField(default=0),
        ),
        migrations.AddField(
            model_name='uniwersity_tkm',
            name='link',
            field=models.URLField(default=1),
        ),
    ]
