# Generated by Django 4.1.3 on 2022-12-01 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0006_remove_uniwersity_global_beyan_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='uniwersity_GLOBAL',
        ),
    ]
