# Generated by Django 4.1.3 on 2022-12-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0007_delete_uniwersity_global'),
    ]

    operations = [
        migrations.CreateModel(
            name='yurtlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.CharField(max_length=50)),
            ],
        ),
    ]
