# Generated by Django 4.1.3 on 2022-12-01 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0009_alter_yurtlar_options_uniwersity_tkm_yurt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniwersity_tkm',
            name='yurt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maglumat.yurtlar'),
        ),
    ]
