# Generated by Django 4.1.3 on 2022-12-01 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0010_alter_uniwersity_tkm_yurt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='uniwersity_TKM',
            new_name='uniwersitetler',
        ),
    ]
