# Generated by Django 4.1.3 on 2022-12-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0011_rename_uniwersity_tkm_uniwersitetler'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uniwersitetler',
            options={'ordering': ['at']},
        ),
        migrations.AddField(
            model_name='uniwersitetler',
            name='chat',
            field=models.URLField(default=1),
        ),
        migrations.AlterField(
            model_name='uniwersitetler',
            name='link',
            field=models.URLField(),
        ),
    ]
