# Generated by Django 4.1.3 on 2022-12-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0012_alter_uniwersitetler_options_uniwersitetler_chat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniwersitetler',
            name='chat',
            field=models.URLField(),
        ),
    ]
