# Generated by Django 4.1.3 on 2022-12-01 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0013_alter_uniwersitetler_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uniwersitetler',
            name='chat',
        ),
    ]
