# Generated by Django 4.1.3 on 2022-12-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0015_teswir'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.CharField(max_length=50)),
                ('gmail', models.EmailField(max_length=254)),
            ],
        ),
    ]
