# Generated by Django 4.1.3 on 2022-12-02 14:28

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0017_register_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
