# Generated by Django 4.1.3 on 2022-12-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0019_register_parol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='parol',
            field=models.CharField(max_length=8),
        ),
    ]
