# Generated by Django 4.1.3 on 2022-12-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0020_alter_register_parol'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('surat', models.ImageField(upload_to='news_images')),
                ('beyan', models.TextField()),
                ('wagt', models.DateField()),
            ],
        ),
    ]
