# Generated by Django 4.1.3 on 2022-12-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0023_rename_title_news_title_tm_news_beyan_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
