# Generated by Django 4.1.3 on 2022-12-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0024_news_title_en_news_title_ru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='beyan_en',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='beyan_ru',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=100),
        ),
    ]
