# Generated by Django 4.1.3 on 2022-12-03 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0025_alter_news_beyan_en_alter_news_beyan_ru_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uniwersitetler',
            options={'ordering': ['at_tm']},
        ),
        migrations.RenameField(
            model_name='uniwersitetler',
            old_name='at',
            new_name='at_tm',
        ),
    ]
