# Generated by Django 4.1.3 on 2022-12-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0027_uniwersitetler_at_en_uniwersitetler_at_ru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniwersitetler',
            name='at_en',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='uniwersitetler',
            name='at_ru',
            field=models.CharField(max_length=200),
        ),
    ]
