# Generated by Django 4.1.3 on 2022-12-05 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0031_alter_yurtlar_options_rename_at_tm_yurtlar_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yurtlar',
            options={'ordering': ['at_tm']},
        ),
        migrations.RenameField(
            model_name='yurtlar',
            old_name='at',
            new_name='at_tm',
        ),
    ]
