# Generated by Django 4.1.3 on 2022-12-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0033_yurtlar_at_en_yurtlar_at_ru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_tm',
            field=models.CharField(max_length=200),
        ),
    ]
